name: Example
on: push
jobs:
  echo:
    runs-on: ubuntu-latest

    steps:
      - run: echo -n -e "HELLO\n !\n World!" > hash.md

      - uses: pCYSl5EDgo/cat@master
        id: hello
        with:
          path: hash.md

      - run: echo $TEXT
        env:
          TEXT: ${{ steps.hello.outputs.text  }}
